### ISSUE TITLE
Clarify blockReports cleanup policy

### ISSUE THREAD

**Issue by ajouve-atih** [kyverno/policy-reporter-plugins#5]
Hello,

I've deployed Kyverno policy-reporter on a cluster with ClusterPolicies set to `Enforce` mode.

To be able to export metrics about blocked resources as well, I've deployed this plugin and I've set the Helm value `plugin.kyverno.blockReports.enabled` to `true`.

So far, everything is working as expected : `PolicyReport` objects are correctly created for blocked resources, Prometheus metrics are also appropriately reflecting these enforced policies.

However, I'm a bit worried by the lifecycle of these objects : is there some sort of  garbage collection process implemented ?

I'm afraid that on the long run these reports could be pilling up and overwhelm the cluster.
Moreover, I'm not interested by having metrics about blocked objects reported for a long time : after all, these objects were never created on the cluster so I just need to export metrics for a short window of time for alerting/dashboarding purpose.

If no such process is implemented, what could be a best practice to adopt ? I was thinking of creating a dedicated [ClusterCleanupPolicy](https://kyverno.io/docs/writing-policies/cleanup/). 
A feature to allow users to set custom labels on reports could be a nice alternative : this way, a `cleanup.kyverno.io/ttl` label would do the trick.

Regards,
Antoine

**Comment by fjogeleit** [comment]
Heyx, thanks for your feedback.

Right now you can configure a limit of results per PolicyReport which means 200 results per namespace as one report per namespace is created.

The workflow with a cleanup policy would be an interesting approach and support for custom labels should be fairly easy. I will take a look on this. But as you can limit it already with an max amount per ns it should not impact your cluster/etcd in a long term.

**Comment by fjogeleit** [comment]
With the latest helm release 3.0.0-rc.2 its possible to configure custom `labels` and `annotations` for the created PolicyReports.

example:

```yaml
plugin:
  kyverno:
    enabled: true
    blockReports:
      enabled: true
      source: Kyverno Event
      policyReports:
        labels:
          test: run
```

**Comment by ajouve-atih** [comment]
> Right now you can configure a limit of results per PolicyReport which means you, per default, 200 results per namespace. The plugin creates only one report per namespace.

Just to make sure that I've fully understood : with this setting, the policy-reporter-plugins will create one report per namespace and this report will contain an history of at most 200 blocked resources ?

Regarding the policyReports labels/annotations, I'm really impressed by how fast you implemented this feature 🤩

Thanks a lot @fjogeleit !

Antoine

**Comment by fjogeleit** [comment]
> Just to make sure that I've fully understood : with this setting, the policy-reporter-plugins will create one report per namespace and this report will contain an history of at most 200 blocked resources ?

correct, you can change this max amount as you prefer but the default is 200.

You're welcome. Thanks for bringing this up.
